### ISSUE TITLE
Atoms & volume

### ISSUE THREAD

**Issue by mdobric** [photonlines/Intuitive-Guide-to-Maxwells-Equations#6]
I don't think that atoms are considered elementary particles and thus have no volume. They are definitely not fundamental particles since they are made up of other particles (electrons, protons, neutrons). I also think that the radius for several atoms has been measured which implies that they do have a volume.
The statement that atoms have no volume is made in the fifth paragraph of the Fields/What is a field? section.

**Comment by photonlines** [comment]
Elementary 'particles' don't really have a shape or a size -- in quantum physics, a particle is represented by its quantum state. If you want to describe that state or location is in space, you get a wave function which tells you how much of that 'particle' is present at any given location. Because there's no technical limit for the size of that region, you can't assign a finite size or volume to a particle! Even if you were to try to do so, it would create issues in space-time! Although physicists like to refer to particles as being point-like, in my opinion - fields and mathematical functions tend to be better models for them. For a good overview and discussion you can reference this link: https://physics.stackexchange.com/questions/122570/what-is-more-fundamental-fields-or-particles 

Hopefully this helps!

**Comment by photonlines** [comment]
Sorry - so just FYI - I didn't realize what your complaint was until just now. I should have used the term 'particle' instead of 'atom' to avoid confusion. I changed the section to use the correct term just now - thanks for the info and for letting me know about the issue!
